apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openanonymiser-dev

resources:
  - ../../base

namePrefix: dev-

images:
  - name: ghcr.io/mwest2020/openanonymiser-light
    newTag: dev

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: openanonymiser
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: api.dev.openanonymiser.commonground.nu
      - op: replace
        path: /spec/tls/0/hosts/0
        value: api.dev.openanonymiser.commonground.nu
      - op: replace
        path: /spec/tls/0/secretName
        value: openanonymiser-dev-tls
    target:
      kind: Ingress
      name: openanonymiser

configMapGenerator:
  - name: openanonymiser-config
    envs:
      - config.env

labels:
  - pairs:
      environment: dev
